# Developer Makefile for common tasks

VENV=.venv
PY=python
PIP=pip

.PHONY: help start init-db migrate makemigrations test

help:
	@echo "Makefile commands:"
	@echo "  start         - Start the FastAPI app (python main.py)"
	@echo "  init-db       - Initialize the database (runs init_db.py)"
	@echo "  migrate       - Run alembic upgrade head"
	@echo "  makemigrations- Create a new alembic revision (autogenerate)"
	@echo "  test          - Run API smoke tests (tests/test_api.py)"

start:
	$(PY) main.py

init-db:
	$(PY) init_db.py

migrate:
	alembic upgrade head

makemigrations:
	alembic revision --autogenerate -m "autogenerated"

test:
	$(PY) tests/test_api.py
